### PR TITLE
Milestone: docs

### PR DESCRIPTION
**Pull request by NataJenkins**
Entity Relationship Diagram for a social media for better understanding of the relationship of elements in the database

### CODE REVIEW

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've made a lot of progress in this milestone.
However, some changes are required before it can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] Your linter checks (GitHub Actions) are not running. Kindly ensure that the checks are running successfully before you request another review.
- [x] Your PR title is not Descriptive. Titles like `Milestone 1`, `Milestone: docs` or `ERD` would have been better.
- [x] Your PR page did not have any description. Kindly summarize what you did in this feature.
- [x] User table should have `image_link` column ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone1/imglink.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] Since user1 and user2 are both from the user table, there should be 2 relationships between the user and friendship table. See the image below for details:



* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
## Changes Required :recycle: 
Hello team. Thanks for making the requested changes. Your ERD diagram looks good and also you've changed the PR's name. :+1:  However there are things to be done before moving on.

- [x]  Kindly fix your GitHub actions. There are no linter checks on your PR.
- [x]  Kindly summarize what you've done in this milestone on your PR. This will help you with the next milestones and improve your understanding about the models.

Again, god job. :smiley: Please fix those issues and submit for a re-review.
If you have a question about the review, feel free to reach out to me via Slack.
_Eyüp Sercan UYGUR_

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Nat Macias Ortiz & Finch Tabilo Sepulveda** 
Good job with your first submission for this project :muscle:  :muscle:
Your project meets most of the requirements :clap: :clap: :clap:  
Just one last detail to improve before you can go ahead:

- [x] Remove 'status' attribute from Likes table
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by ebeagusamuel — APPROVED** [review]
# Project Approved :100: 
#### Your project has now met the basic requirements and is now approved. You can now move to the next milestone.
#### Goodluck
slack(@ebeagusamuel)

**Pull request merged**
