### PR TITLE
Milestone 2: Friendship v2

### PR DESCRIPTION
**Pull request by NataJenkins**
relation between users with friendship defining associations with SQL query

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, everything works fine, but there are a few more things required. 
### General

- [ ]  Instead of processing objects in application memory, let's define association with SQL query.
````ruby
# confirm friends
has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships

# pending_friends
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend

#friend_requests
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships

`````
 - [ ] Let's include unit test .
 - [ ] I couldn't run the project due to the error below.


 
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required ♻🛑**

<hr>

Hello Team, great job so far you've done on this project, I can see the effort made and it's almost professional. Please do the following changes before submitting for a re-review.

- [ ] Please add more descriptive Pull Request Header
- [ ] Please add more descriptive Pull Request Body
- [ ] Please refactor any logic code written in views, check application.html.erb and users/show.html.erb files

<hr>

## **[OPTIONAL]**

<hr>

- It'd only take 5 mins to deploy your app on a live demo link i.e. Heroku, for easier access for future viewers.

<hr>

Good luck and happy coding 👨‍💻💻

**Comment by Nexch** [comment]
> # **Changes Required recyclestop_sign**
> Hello Team, great job so far you've done on this project, I can see the effort made and it's almost professional. Please do the following changes before submitting for a re-review.
> 
> * [ ]  Please add more descriptive Pull Request Header
> * [ ]  Please add more descriptive Pull Request Body
> * [ ]  Please refactor any logic code written in views, check application.html.erb and users/show.html.erb files
> 
> ## **[OPTIONAL]**
> * It'd only take 5 mins to deploy your app on a live demo link i.e. Heroku, for easier access for future viewers.
> 
> Good luck and happy coding

the file application.html.erb was created by https://github.com/bolah2009 and https://github.com/nidalaa if you need anything fe free to talk to them

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've put in a lot of effort in this project. Everything looks good, except for some minor improvements. Let's dive in!__

**[ REQUIRED CHANGES ]**

- [x] You still have logic in your views (see `app/views/users/_user.html.erb`). Kindly move all view-related logic to the helper module.
- [ ] Please add more test cases: ensure that your tests cover both positive and negative scenarios.



* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @NataJenkins**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [x] You tested everything but you forgot to test the associations. please make sure you add tests for all of the associations.



---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by teekaytech — APPROVED** [review]
### Status: Approved :green_circle: 

### Congratulations team, this milestone has passed all the mandatory requirements. It is therefore approved :heavy_check_mark:


Again, congratulations, you can merge to the development branch.
Good luck with your next milestone.

* * * 
**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Pull request merged**
