### PR TITLE
Milestone 2: Friendship v1

### PR DESCRIPTION
**Pull request by NataJenkins**
Create a model with associations and all requested features for friendships

### CODE REVIEW

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Require changes 🌳 ♲
Hi @NataJenkins  and @Nexch , I am  [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  I appreciate your hard work in achieving this milestone; you did very well.

[Required]

- [x] There should be buttons to accept friendships and reject friendship requests
- [x] Add a request friendship and a reject friend friendship button
- [x] There should be a button to invite another user invitations to the user must be shown
- [x] Display invitations to the user
- [x] Add unit test and integration tests

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes :recycle: 

Great job so far @team :clap: :clap: :clap:, but you still have some changes :hammer: :toolbox: :wrench: to take care of in order to get this project approved :checkered_flag:.

Please check the comments below:
:point_down: :point_down: :point_down: :point_down: :point_down: 

## Required Changes :red_circle:: 

- [x] please remove unnecessary views, what is this:
image

- [x] Add a request friendship and a reject friend friendship button, on the all users page.

- [x] There is a button to invite user to friendship on the user's list page and on the single-user page.

- [x] Posts timeline includes posts written by logged-in user and their friends.

- [x] Add unit tests and Integration tests as suggested by the previous TSE.

### Please make all the required changes before you submit another code review.

## Happy Coding :tophat: 
_Please feel free to contact me on slack if you have any questions or need help_
## _Zakariae El Mejdki_

**Review by javitocor — CHANGES_REQUESTED** [review]
# STATUS CHANGES REQUIRED 🛑 

Hello team! 👋 
I cannot see  the changes requested by the previous TSE implemented 🤔 
Kindly add the testing and the friendship buttons to your project 💪 
Once done, request  a new code  review ⏩ 
Good luck! 😺

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes Required 🛑

## Hello team 👋,

**Great job implementing the requested changes. However, there are still a few requirements needed.**

1). **When I create a post, I cannot see it on the timeline page. though I see a flash message that the post was created successfully.**

2). **I have two users, Jen and Mercy, and they are not friends. When I log in as Mercy, I expect to see an add friend button/ link next to Jen's name on the user list page which is shown on the screenshot below. Also, see a [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from pathwright on this requirement.**
usersList

3).  **I should not see add friend button/link in my profile page when I am the logged-in user.**

4). **I have Jen who sends Mercy a friend request when she visits Mercy's profile. When I log in as Mercy, I do not see accept and reject links/buttons anywhere. Also, when Jen clicks the add friend button/link in Mercy's profile, it should be disabled so she doesn't send multiple friend requests to Mercy.**

6). **Jen and Mercy are not friends. So when I log in as Jen and visit Mercy's profile, I should not see her posts. That should happen after we are friends.**

7). **You spec tests should have a directory structure. You `models` tests should reside in `spec/models` directory, feature tests should reside in `spec/features` directory, etc.**

8). **You only wrote two tests from your `models` directory, `comment.rb` and `post.rb`. Please write tests for all the other files too. Also, you only wrote validation tests. Remember to add association tests and method tests for any of the file that has methods in them that are not private, e.g `friendship.rb`.**

9). **Write features tests for all the other view files other than users.**
10). **Add tests for your helpers.**

## Happy coding 🥂.

**PS: You can reach me on slack (Rose Wanjohi).**

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **REQUIRED CHANGES 🛑**

<hr>

Hey there 👍 I see that you've done 0 changes since the last review done by the previous TSE.
Please do the requested changes and make sure your app is working properly before submitting for a re-review.

<hr>

Good luck and happy coding 👨‍💻💻

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @NataJenkins and @Nexch  ! :wave: :wave:

#### You have done well so far :clap: However, you have not finished all the previously requested changes. Kindly work on them and submit them for another code review.


**Recommended**

- [ ] When I create a post, I cannot see it on the timeline page. 
It shows me an error, see below for the error. It breaks the app and restricts me from navigating the app until I delete the posts using the console.

Screenshot (28)

- [ ] When I accept a friend request, it shows that I still have no friends. Please fix this.
- [ ] The buttons on the profile page should be properly arranged, It's hard to tell which button shows the list of friends and which is for sending the request.
- [ ] You spec tests should have a directory structure. Your model tests should reside in the spec/models directory, feature tests should reside in the spec/features directory, etc.
- [ ] Add more tests, both unit, and integration tests. Also, add more test cases covering the app's functionality.
- [ ] You only wrote two tests from your models' directory, comment.rb and post.rb. Please write tests for all the other files too. Also, you only wrote validation tests. Remember to add association tests and method tests for any of the files that have methods in them that are not private, e.g friendship.rb.

- [ ]  Write features tests for all the other view files other than users.
- [ ]  Add tests for your helpers.


__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [x] The button for sending a friendship request should be disabled, better should not appear when these conditions are met.
  - [x] Current User should not see the button on his name.
  - [x] Current User should no see the button once he already has accepted a friendship.
  - [x] The **Add Friend** in the profile of each user should be also a button.
  - NOTE: The other solution could be  making the error message an error message with a red color and a better description of why is not possible to do the action on each case instead of only showing the message **Nop**, but is better to hide the button when is not required.
 
- [x] The specs files should be separated, into features, models, helpers, controllers.... etc. Use `rails generate rspec:____`. This article could be useful to do it in an automatic way in the future and to fix today's issue: [LINK](https://relishapp.com/rspec/rspec-rails/docs/generators)
- [x] Erase all pending specs, or better, complete them.

### [OPTIONAL]  :yellow_circle:  

- [ ] Error messages don't match the background color. The error should be red, warnings should be yellow, and valid actions should be green.
- [ ] The messages for valid and invalid actions are not as descriptive for the user, please think of better messages for each action. Example
**BAD**  Friendship was saved correctly
**GOOD** You're friendship request was sent!

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [x] The next issue is still persistant

> The button for sending a friendship request should be disabled, better should not appear when these conditions are met.
> * [x]  Current User should not see the button on his name.
> * [x]  Current User should no see the button once he already has accepted a friendship.
> * [x]  The **Add Friend** in the profile of each user should be also a button.

image
image


## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Review by MahmoudBakr23 — APPROVED** [review]
# **Approved ✔✔**

<hr>

Congratulations on completing this project and all the requested changes.
You can now merge and submit.

<hr>

## **[OPTIONAL]**

- For best practice, try to move the invites notifications from the "All Users" page to its relative user profile page.

<hr>

Good luck on the next and happy coding 👨‍💻💻

**Pull request merged**
